package org.jlobato.gpro.dao.mybatis.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jlobato.gpro.dao.mybatis.model.ManagerResult;
import org.jlobato.gpro.dao.mybatis.model.ManagerResultExample;

public interface ManagerResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_result
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    long countByExample(ManagerResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_result
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    int deleteByExample(ManagerResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_result
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    int deleteByPrimaryKey(Integer idManagerResult);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_result
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    int insert(ManagerResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_result
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    int insertSelective(ManagerResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_result
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    List<ManagerResult> selectByExample(ManagerResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_result
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    ManagerResult selectByPrimaryKey(Integer idManagerResult);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_result
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    int updateByExampleSelective(@Param("record") ManagerResult record, @Param("example") ManagerResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_result
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    int updateByExample(@Param("record") ManagerResult record, @Param("example") ManagerResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_result
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    int updateByPrimaryKeySelective(ManagerResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_result
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    int updateByPrimaryKey(ManagerResult record);
}