package org.jlobato.gpro.dao.mybatis.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jlobato.gpro.dao.mybatis.model.Pitstop;
import org.jlobato.gpro.dao.mybatis.model.PitstopExample;

public interface PitstopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    long countByExample(PitstopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    int deleteByExample(PitstopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    int deleteByPrimaryKey(Integer idPitstop);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    int insert(Pitstop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    int insertSelective(Pitstop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    List<Pitstop> selectByExample(PitstopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    Pitstop selectByPrimaryKey(Integer idPitstop);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    int updateByExampleSelective(@Param("record") Pitstop record, @Param("example") PitstopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    int updateByExample(@Param("record") Pitstop record, @Param("example") PitstopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    int updateByPrimaryKeySelective(Pitstop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    int updateByPrimaryKey(Pitstop record);
}