package org.jlobato.gpro.dao.mybatis.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jlobato.gpro.dao.mybatis.model.TyreCompound;
import org.jlobato.gpro.dao.mybatis.model.TyreCompoundExample;

public interface TyreCompoundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyrecompound
     *
     * @mbg.generated Sat Oct 19 19:30:10 CEST 2024
     */
    long countByExample(TyreCompoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyrecompound
     *
     * @mbg.generated Sat Oct 19 19:30:10 CEST 2024
     */
    int deleteByExample(TyreCompoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyrecompound
     *
     * @mbg.generated Sat Oct 19 19:30:10 CEST 2024
     */
    int deleteByPrimaryKey(Integer idTyrecompound);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyrecompound
     *
     * @mbg.generated Sat Oct 19 19:30:10 CEST 2024
     */
    int insert(TyreCompound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyrecompound
     *
     * @mbg.generated Sat Oct 19 19:30:10 CEST 2024
     */
    int insertSelective(TyreCompound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyrecompound
     *
     * @mbg.generated Sat Oct 19 19:30:10 CEST 2024
     */
    List<TyreCompound> selectByExample(TyreCompoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyrecompound
     *
     * @mbg.generated Sat Oct 19 19:30:10 CEST 2024
     */
    TyreCompound selectByPrimaryKey(Integer idTyrecompound);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyrecompound
     *
     * @mbg.generated Sat Oct 19 19:30:10 CEST 2024
     */
    int updateByExampleSelective(@Param("record") TyreCompound record, @Param("example") TyreCompoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyrecompound
     *
     * @mbg.generated Sat Oct 19 19:30:10 CEST 2024
     */
    int updateByExample(@Param("record") TyreCompound record, @Param("example") TyreCompoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyrecompound
     *
     * @mbg.generated Sat Oct 19 19:30:10 CEST 2024
     */
    int updateByPrimaryKeySelective(TyreCompound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyrecompound
     *
     * @mbg.generated Sat Oct 19 19:30:10 CEST 2024
     */
    int updateByPrimaryKey(TyreCompound record);
}