package org.jlobato.gpro.dao.mybatis.model;

import java.io.Serializable;

public class Category implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    private Short idCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.code_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    private String codeCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.description_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    private String descriptionCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.lvl_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    private Short lvlCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.code_alt_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    private String codeAltCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id_category
     *
     * @return the value of category.id_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public Short getIdCategory() {
        return idCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public Category withIdCategory(Short idCategory) {
        this.setIdCategory(idCategory);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id_category
     *
     * @param idCategory the value for category.id_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public void setIdCategory(Short idCategory) {
        this.idCategory = idCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.code_category
     *
     * @return the value of category.code_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public String getCodeCategory() {
        return codeCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public Category withCodeCategory(String codeCategory) {
        this.setCodeCategory(codeCategory);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.code_category
     *
     * @param codeCategory the value for category.code_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public void setCodeCategory(String codeCategory) {
        this.codeCategory = codeCategory == null ? null : codeCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.description_category
     *
     * @return the value of category.description_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public String getDescriptionCategory() {
        return descriptionCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public Category withDescriptionCategory(String descriptionCategory) {
        this.setDescriptionCategory(descriptionCategory);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.description_category
     *
     * @param descriptionCategory the value for category.description_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public void setDescriptionCategory(String descriptionCategory) {
        this.descriptionCategory = descriptionCategory == null ? null : descriptionCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.lvl_category
     *
     * @return the value of category.lvl_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public Short getLvlCategory() {
        return lvlCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public Category withLvlCategory(Short lvlCategory) {
        this.setLvlCategory(lvlCategory);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.lvl_category
     *
     * @param lvlCategory the value for category.lvl_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public void setLvlCategory(Short lvlCategory) {
        this.lvlCategory = lvlCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.code_alt_category
     *
     * @return the value of category.code_alt_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public String getCodeAltCategory() {
        return codeAltCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public Category withCodeAltCategory(String codeAltCategory) {
        this.setCodeAltCategory(codeAltCategory);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.code_alt_category
     *
     * @param codeAltCategory the value for category.code_alt_category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    public void setCodeAltCategory(String codeAltCategory) {
        this.codeAltCategory = codeAltCategory == null ? null : codeAltCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Nov 06 02:38:04 CET 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idCategory=").append(idCategory);
        sb.append(", codeCategory=").append(codeCategory);
        sb.append(", descriptionCategory=").append(descriptionCategory);
        sb.append(", lvlCategory=").append(lvlCategory);
        sb.append(", codeAltCategory=").append(codeAltCategory);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}