package org.jlobato.gpro.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class CupStandingsSnapshotExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    public CupStandingsSnapshotExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdSeasonIsNull() {
            addCriterion("id_season is null");
            return (Criteria) this;
        }

        public Criteria andIdSeasonIsNotNull() {
            addCriterion("id_season is not null");
            return (Criteria) this;
        }

        public Criteria andIdSeasonEqualTo(Short value) {
            addCriterion("id_season =", value, "idSeason");
            return (Criteria) this;
        }

        public Criteria andIdSeasonNotEqualTo(Short value) {
            addCriterion("id_season <>", value, "idSeason");
            return (Criteria) this;
        }

        public Criteria andIdSeasonGreaterThan(Short value) {
            addCriterion("id_season >", value, "idSeason");
            return (Criteria) this;
        }

        public Criteria andIdSeasonGreaterThanOrEqualTo(Short value) {
            addCriterion("id_season >=", value, "idSeason");
            return (Criteria) this;
        }

        public Criteria andIdSeasonLessThan(Short value) {
            addCriterion("id_season <", value, "idSeason");
            return (Criteria) this;
        }

        public Criteria andIdSeasonLessThanOrEqualTo(Short value) {
            addCriterion("id_season <=", value, "idSeason");
            return (Criteria) this;
        }

        public Criteria andIdSeasonIn(List<Short> values) {
            addCriterion("id_season in", values, "idSeason");
            return (Criteria) this;
        }

        public Criteria andIdSeasonNotIn(List<Short> values) {
            addCriterion("id_season not in", values, "idSeason");
            return (Criteria) this;
        }

        public Criteria andIdSeasonBetween(Short value1, Short value2) {
            addCriterion("id_season between", value1, value2, "idSeason");
            return (Criteria) this;
        }

        public Criteria andIdSeasonNotBetween(Short value1, Short value2) {
            addCriterion("id_season not between", value1, value2, "idSeason");
            return (Criteria) this;
        }

        public Criteria andIdTeamIsNull() {
            addCriterion("id_team is null");
            return (Criteria) this;
        }

        public Criteria andIdTeamIsNotNull() {
            addCriterion("id_team is not null");
            return (Criteria) this;
        }

        public Criteria andIdTeamEqualTo(Short value) {
            addCriterion("id_team =", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamNotEqualTo(Short value) {
            addCriterion("id_team <>", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamGreaterThan(Short value) {
            addCriterion("id_team >", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamGreaterThanOrEqualTo(Short value) {
            addCriterion("id_team >=", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamLessThan(Short value) {
            addCriterion("id_team <", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamLessThanOrEqualTo(Short value) {
            addCriterion("id_team <=", value, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamIn(List<Short> values) {
            addCriterion("id_team in", values, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamNotIn(List<Short> values) {
            addCriterion("id_team not in", values, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamBetween(Short value1, Short value2) {
            addCriterion("id_team between", value1, value2, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdTeamNotBetween(Short value1, Short value2) {
            addCriterion("id_team not between", value1, value2, "idTeam");
            return (Criteria) this;
        }

        public Criteria andIdRaceIsNull() {
            addCriterion("id_race is null");
            return (Criteria) this;
        }

        public Criteria andIdRaceIsNotNull() {
            addCriterion("id_race is not null");
            return (Criteria) this;
        }

        public Criteria andIdRaceEqualTo(Short value) {
            addCriterion("id_race =", value, "idRace");
            return (Criteria) this;
        }

        public Criteria andIdRaceNotEqualTo(Short value) {
            addCriterion("id_race <>", value, "idRace");
            return (Criteria) this;
        }

        public Criteria andIdRaceGreaterThan(Short value) {
            addCriterion("id_race >", value, "idRace");
            return (Criteria) this;
        }

        public Criteria andIdRaceGreaterThanOrEqualTo(Short value) {
            addCriterion("id_race >=", value, "idRace");
            return (Criteria) this;
        }

        public Criteria andIdRaceLessThan(Short value) {
            addCriterion("id_race <", value, "idRace");
            return (Criteria) this;
        }

        public Criteria andIdRaceLessThanOrEqualTo(Short value) {
            addCriterion("id_race <=", value, "idRace");
            return (Criteria) this;
        }

        public Criteria andIdRaceIn(List<Short> values) {
            addCriterion("id_race in", values, "idRace");
            return (Criteria) this;
        }

        public Criteria andIdRaceNotIn(List<Short> values) {
            addCriterion("id_race not in", values, "idRace");
            return (Criteria) this;
        }

        public Criteria andIdRaceBetween(Short value1, Short value2) {
            addCriterion("id_race between", value1, value2, "idRace");
            return (Criteria) this;
        }

        public Criteria andIdRaceNotBetween(Short value1, Short value2) {
            addCriterion("id_race not between", value1, value2, "idRace");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf1IsNull() {
            addCriterion("id_manager_qf1 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf1IsNotNull() {
            addCriterion("id_manager_qf1 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf1EqualTo(Short value) {
            addCriterion("id_manager_qf1 =", value, "idManagerQf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf1NotEqualTo(Short value) {
            addCriterion("id_manager_qf1 <>", value, "idManagerQf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf1GreaterThan(Short value) {
            addCriterion("id_manager_qf1 >", value, "idManagerQf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf1GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf1 >=", value, "idManagerQf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf1LessThan(Short value) {
            addCriterion("id_manager_qf1 <", value, "idManagerQf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf1LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf1 <=", value, "idManagerQf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf1In(List<Short> values) {
            addCriterion("id_manager_qf1 in", values, "idManagerQf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf1NotIn(List<Short> values) {
            addCriterion("id_manager_qf1 not in", values, "idManagerQf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf1Between(Short value1, Short value2) {
            addCriterion("id_manager_qf1 between", value1, value2, "idManagerQf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf1NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_qf1 not between", value1, value2, "idManagerQf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf2IsNull() {
            addCriterion("id_manager_qf2 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf2IsNotNull() {
            addCriterion("id_manager_qf2 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf2EqualTo(Short value) {
            addCriterion("id_manager_qf2 =", value, "idManagerQf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf2NotEqualTo(Short value) {
            addCriterion("id_manager_qf2 <>", value, "idManagerQf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf2GreaterThan(Short value) {
            addCriterion("id_manager_qf2 >", value, "idManagerQf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf2GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf2 >=", value, "idManagerQf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf2LessThan(Short value) {
            addCriterion("id_manager_qf2 <", value, "idManagerQf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf2LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf2 <=", value, "idManagerQf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf2In(List<Short> values) {
            addCriterion("id_manager_qf2 in", values, "idManagerQf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf2NotIn(List<Short> values) {
            addCriterion("id_manager_qf2 not in", values, "idManagerQf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf2Between(Short value1, Short value2) {
            addCriterion("id_manager_qf2 between", value1, value2, "idManagerQf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf2NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_qf2 not between", value1, value2, "idManagerQf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf3IsNull() {
            addCriterion("id_manager_qf3 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf3IsNotNull() {
            addCriterion("id_manager_qf3 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf3EqualTo(Short value) {
            addCriterion("id_manager_qf3 =", value, "idManagerQf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf3NotEqualTo(Short value) {
            addCriterion("id_manager_qf3 <>", value, "idManagerQf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf3GreaterThan(Short value) {
            addCriterion("id_manager_qf3 >", value, "idManagerQf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf3GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf3 >=", value, "idManagerQf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf3LessThan(Short value) {
            addCriterion("id_manager_qf3 <", value, "idManagerQf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf3LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf3 <=", value, "idManagerQf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf3In(List<Short> values) {
            addCriterion("id_manager_qf3 in", values, "idManagerQf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf3NotIn(List<Short> values) {
            addCriterion("id_manager_qf3 not in", values, "idManagerQf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf3Between(Short value1, Short value2) {
            addCriterion("id_manager_qf3 between", value1, value2, "idManagerQf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf3NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_qf3 not between", value1, value2, "idManagerQf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf4IsNull() {
            addCriterion("id_manager_qf4 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf4IsNotNull() {
            addCriterion("id_manager_qf4 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf4EqualTo(Short value) {
            addCriterion("id_manager_qf4 =", value, "idManagerQf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf4NotEqualTo(Short value) {
            addCriterion("id_manager_qf4 <>", value, "idManagerQf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf4GreaterThan(Short value) {
            addCriterion("id_manager_qf4 >", value, "idManagerQf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf4GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf4 >=", value, "idManagerQf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf4LessThan(Short value) {
            addCriterion("id_manager_qf4 <", value, "idManagerQf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf4LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf4 <=", value, "idManagerQf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf4In(List<Short> values) {
            addCriterion("id_manager_qf4 in", values, "idManagerQf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf4NotIn(List<Short> values) {
            addCriterion("id_manager_qf4 not in", values, "idManagerQf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf4Between(Short value1, Short value2) {
            addCriterion("id_manager_qf4 between", value1, value2, "idManagerQf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf4NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_qf4 not between", value1, value2, "idManagerQf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf5IsNull() {
            addCriterion("id_manager_qf5 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf5IsNotNull() {
            addCriterion("id_manager_qf5 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf5EqualTo(Short value) {
            addCriterion("id_manager_qf5 =", value, "idManagerQf5");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf5NotEqualTo(Short value) {
            addCriterion("id_manager_qf5 <>", value, "idManagerQf5");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf5GreaterThan(Short value) {
            addCriterion("id_manager_qf5 >", value, "idManagerQf5");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf5GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf5 >=", value, "idManagerQf5");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf5LessThan(Short value) {
            addCriterion("id_manager_qf5 <", value, "idManagerQf5");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf5LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf5 <=", value, "idManagerQf5");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf5In(List<Short> values) {
            addCriterion("id_manager_qf5 in", values, "idManagerQf5");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf5NotIn(List<Short> values) {
            addCriterion("id_manager_qf5 not in", values, "idManagerQf5");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf5Between(Short value1, Short value2) {
            addCriterion("id_manager_qf5 between", value1, value2, "idManagerQf5");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf5NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_qf5 not between", value1, value2, "idManagerQf5");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf6IsNull() {
            addCriterion("id_manager_qf6 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf6IsNotNull() {
            addCriterion("id_manager_qf6 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf6EqualTo(Short value) {
            addCriterion("id_manager_qf6 =", value, "idManagerQf6");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf6NotEqualTo(Short value) {
            addCriterion("id_manager_qf6 <>", value, "idManagerQf6");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf6GreaterThan(Short value) {
            addCriterion("id_manager_qf6 >", value, "idManagerQf6");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf6GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf6 >=", value, "idManagerQf6");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf6LessThan(Short value) {
            addCriterion("id_manager_qf6 <", value, "idManagerQf6");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf6LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf6 <=", value, "idManagerQf6");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf6In(List<Short> values) {
            addCriterion("id_manager_qf6 in", values, "idManagerQf6");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf6NotIn(List<Short> values) {
            addCriterion("id_manager_qf6 not in", values, "idManagerQf6");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf6Between(Short value1, Short value2) {
            addCriterion("id_manager_qf6 between", value1, value2, "idManagerQf6");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf6NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_qf6 not between", value1, value2, "idManagerQf6");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf7IsNull() {
            addCriterion("id_manager_qf7 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf7IsNotNull() {
            addCriterion("id_manager_qf7 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf7EqualTo(Short value) {
            addCriterion("id_manager_qf7 =", value, "idManagerQf7");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf7NotEqualTo(Short value) {
            addCriterion("id_manager_qf7 <>", value, "idManagerQf7");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf7GreaterThan(Short value) {
            addCriterion("id_manager_qf7 >", value, "idManagerQf7");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf7GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf7 >=", value, "idManagerQf7");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf7LessThan(Short value) {
            addCriterion("id_manager_qf7 <", value, "idManagerQf7");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf7LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf7 <=", value, "idManagerQf7");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf7In(List<Short> values) {
            addCriterion("id_manager_qf7 in", values, "idManagerQf7");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf7NotIn(List<Short> values) {
            addCriterion("id_manager_qf7 not in", values, "idManagerQf7");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf7Between(Short value1, Short value2) {
            addCriterion("id_manager_qf7 between", value1, value2, "idManagerQf7");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf7NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_qf7 not between", value1, value2, "idManagerQf7");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf8IsNull() {
            addCriterion("id_manager_qf8 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf8IsNotNull() {
            addCriterion("id_manager_qf8 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf8EqualTo(Short value) {
            addCriterion("id_manager_qf8 =", value, "idManagerQf8");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf8NotEqualTo(Short value) {
            addCriterion("id_manager_qf8 <>", value, "idManagerQf8");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf8GreaterThan(Short value) {
            addCriterion("id_manager_qf8 >", value, "idManagerQf8");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf8GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf8 >=", value, "idManagerQf8");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf8LessThan(Short value) {
            addCriterion("id_manager_qf8 <", value, "idManagerQf8");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf8LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_qf8 <=", value, "idManagerQf8");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf8In(List<Short> values) {
            addCriterion("id_manager_qf8 in", values, "idManagerQf8");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf8NotIn(List<Short> values) {
            addCriterion("id_manager_qf8 not in", values, "idManagerQf8");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf8Between(Short value1, Short value2) {
            addCriterion("id_manager_qf8 between", value1, value2, "idManagerQf8");
            return (Criteria) this;
        }

        public Criteria andIdManagerQf8NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_qf8 not between", value1, value2, "idManagerQf8");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf1IsNull() {
            addCriterion("score_manager_qf1 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf1IsNotNull() {
            addCriterion("score_manager_qf1 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf1EqualTo(BigDecimal value) {
            addCriterion("score_manager_qf1 =", value, "scoreManagerQf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf1NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf1 <>", value, "scoreManagerQf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf1GreaterThan(BigDecimal value) {
            addCriterion("score_manager_qf1 >", value, "scoreManagerQf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf1 >=", value, "scoreManagerQf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf1LessThan(BigDecimal value) {
            addCriterion("score_manager_qf1 <", value, "scoreManagerQf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf1 <=", value, "scoreManagerQf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf1In(List<BigDecimal> values) {
            addCriterion("score_manager_qf1 in", values, "scoreManagerQf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf1NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_qf1 not in", values, "scoreManagerQf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf1 between", value1, value2, "scoreManagerQf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf1 not between", value1, value2, "scoreManagerQf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf2IsNull() {
            addCriterion("score_manager_qf2 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf2IsNotNull() {
            addCriterion("score_manager_qf2 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf2EqualTo(BigDecimal value) {
            addCriterion("score_manager_qf2 =", value, "scoreManagerQf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf2NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf2 <>", value, "scoreManagerQf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf2GreaterThan(BigDecimal value) {
            addCriterion("score_manager_qf2 >", value, "scoreManagerQf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf2 >=", value, "scoreManagerQf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf2LessThan(BigDecimal value) {
            addCriterion("score_manager_qf2 <", value, "scoreManagerQf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf2 <=", value, "scoreManagerQf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf2In(List<BigDecimal> values) {
            addCriterion("score_manager_qf2 in", values, "scoreManagerQf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf2NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_qf2 not in", values, "scoreManagerQf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf2 between", value1, value2, "scoreManagerQf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf2 not between", value1, value2, "scoreManagerQf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf3IsNull() {
            addCriterion("score_manager_qf3 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf3IsNotNull() {
            addCriterion("score_manager_qf3 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf3EqualTo(BigDecimal value) {
            addCriterion("score_manager_qf3 =", value, "scoreManagerQf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf3NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf3 <>", value, "scoreManagerQf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf3GreaterThan(BigDecimal value) {
            addCriterion("score_manager_qf3 >", value, "scoreManagerQf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf3GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf3 >=", value, "scoreManagerQf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf3LessThan(BigDecimal value) {
            addCriterion("score_manager_qf3 <", value, "scoreManagerQf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf3LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf3 <=", value, "scoreManagerQf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf3In(List<BigDecimal> values) {
            addCriterion("score_manager_qf3 in", values, "scoreManagerQf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf3NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_qf3 not in", values, "scoreManagerQf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf3Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf3 between", value1, value2, "scoreManagerQf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf3NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf3 not between", value1, value2, "scoreManagerQf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf4IsNull() {
            addCriterion("score_manager_qf4 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf4IsNotNull() {
            addCriterion("score_manager_qf4 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf4EqualTo(BigDecimal value) {
            addCriterion("score_manager_qf4 =", value, "scoreManagerQf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf4NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf4 <>", value, "scoreManagerQf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf4GreaterThan(BigDecimal value) {
            addCriterion("score_manager_qf4 >", value, "scoreManagerQf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf4GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf4 >=", value, "scoreManagerQf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf4LessThan(BigDecimal value) {
            addCriterion("score_manager_qf4 <", value, "scoreManagerQf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf4LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf4 <=", value, "scoreManagerQf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf4In(List<BigDecimal> values) {
            addCriterion("score_manager_qf4 in", values, "scoreManagerQf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf4NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_qf4 not in", values, "scoreManagerQf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf4Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf4 between", value1, value2, "scoreManagerQf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf4NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf4 not between", value1, value2, "scoreManagerQf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf5IsNull() {
            addCriterion("score_manager_qf5 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf5IsNotNull() {
            addCriterion("score_manager_qf5 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf5EqualTo(BigDecimal value) {
            addCriterion("score_manager_qf5 =", value, "scoreManagerQf5");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf5NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf5 <>", value, "scoreManagerQf5");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf5GreaterThan(BigDecimal value) {
            addCriterion("score_manager_qf5 >", value, "scoreManagerQf5");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf5GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf5 >=", value, "scoreManagerQf5");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf5LessThan(BigDecimal value) {
            addCriterion("score_manager_qf5 <", value, "scoreManagerQf5");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf5LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf5 <=", value, "scoreManagerQf5");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf5In(List<BigDecimal> values) {
            addCriterion("score_manager_qf5 in", values, "scoreManagerQf5");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf5NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_qf5 not in", values, "scoreManagerQf5");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf5Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf5 between", value1, value2, "scoreManagerQf5");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf5NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf5 not between", value1, value2, "scoreManagerQf5");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf6IsNull() {
            addCriterion("score_manager_qf6 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf6IsNotNull() {
            addCriterion("score_manager_qf6 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf6EqualTo(BigDecimal value) {
            addCriterion("score_manager_qf6 =", value, "scoreManagerQf6");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf6NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf6 <>", value, "scoreManagerQf6");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf6GreaterThan(BigDecimal value) {
            addCriterion("score_manager_qf6 >", value, "scoreManagerQf6");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf6GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf6 >=", value, "scoreManagerQf6");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf6LessThan(BigDecimal value) {
            addCriterion("score_manager_qf6 <", value, "scoreManagerQf6");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf6LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf6 <=", value, "scoreManagerQf6");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf6In(List<BigDecimal> values) {
            addCriterion("score_manager_qf6 in", values, "scoreManagerQf6");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf6NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_qf6 not in", values, "scoreManagerQf6");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf6Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf6 between", value1, value2, "scoreManagerQf6");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf6NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf6 not between", value1, value2, "scoreManagerQf6");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf7IsNull() {
            addCriterion("score_manager_qf7 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf7IsNotNull() {
            addCriterion("score_manager_qf7 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf7EqualTo(BigDecimal value) {
            addCriterion("score_manager_qf7 =", value, "scoreManagerQf7");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf7NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf7 <>", value, "scoreManagerQf7");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf7GreaterThan(BigDecimal value) {
            addCriterion("score_manager_qf7 >", value, "scoreManagerQf7");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf7GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf7 >=", value, "scoreManagerQf7");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf7LessThan(BigDecimal value) {
            addCriterion("score_manager_qf7 <", value, "scoreManagerQf7");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf7LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf7 <=", value, "scoreManagerQf7");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf7In(List<BigDecimal> values) {
            addCriterion("score_manager_qf7 in", values, "scoreManagerQf7");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf7NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_qf7 not in", values, "scoreManagerQf7");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf7Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf7 between", value1, value2, "scoreManagerQf7");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf7NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf7 not between", value1, value2, "scoreManagerQf7");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf8IsNull() {
            addCriterion("score_manager_qf8 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf8IsNotNull() {
            addCriterion("score_manager_qf8 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf8EqualTo(BigDecimal value) {
            addCriterion("score_manager_qf8 =", value, "scoreManagerQf8");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf8NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf8 <>", value, "scoreManagerQf8");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf8GreaterThan(BigDecimal value) {
            addCriterion("score_manager_qf8 >", value, "scoreManagerQf8");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf8GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf8 >=", value, "scoreManagerQf8");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf8LessThan(BigDecimal value) {
            addCriterion("score_manager_qf8 <", value, "scoreManagerQf8");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf8LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_qf8 <=", value, "scoreManagerQf8");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf8In(List<BigDecimal> values) {
            addCriterion("score_manager_qf8 in", values, "scoreManagerQf8");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf8NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_qf8 not in", values, "scoreManagerQf8");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf8Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf8 between", value1, value2, "scoreManagerQf8");
            return (Criteria) this;
        }

        public Criteria andScoreManagerQf8NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_qf8 not between", value1, value2, "scoreManagerQf8");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf1IsNull() {
            addCriterion("id_manager_sf1 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf1IsNotNull() {
            addCriterion("id_manager_sf1 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf1EqualTo(Short value) {
            addCriterion("id_manager_sf1 =", value, "idManagerSf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf1NotEqualTo(Short value) {
            addCriterion("id_manager_sf1 <>", value, "idManagerSf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf1GreaterThan(Short value) {
            addCriterion("id_manager_sf1 >", value, "idManagerSf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf1GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_sf1 >=", value, "idManagerSf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf1LessThan(Short value) {
            addCriterion("id_manager_sf1 <", value, "idManagerSf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf1LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_sf1 <=", value, "idManagerSf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf1In(List<Short> values) {
            addCriterion("id_manager_sf1 in", values, "idManagerSf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf1NotIn(List<Short> values) {
            addCriterion("id_manager_sf1 not in", values, "idManagerSf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf1Between(Short value1, Short value2) {
            addCriterion("id_manager_sf1 between", value1, value2, "idManagerSf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf1NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_sf1 not between", value1, value2, "idManagerSf1");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf2IsNull() {
            addCriterion("id_manager_sf2 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf2IsNotNull() {
            addCriterion("id_manager_sf2 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf2EqualTo(Short value) {
            addCriterion("id_manager_sf2 =", value, "idManagerSf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf2NotEqualTo(Short value) {
            addCriterion("id_manager_sf2 <>", value, "idManagerSf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf2GreaterThan(Short value) {
            addCriterion("id_manager_sf2 >", value, "idManagerSf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf2GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_sf2 >=", value, "idManagerSf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf2LessThan(Short value) {
            addCriterion("id_manager_sf2 <", value, "idManagerSf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf2LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_sf2 <=", value, "idManagerSf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf2In(List<Short> values) {
            addCriterion("id_manager_sf2 in", values, "idManagerSf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf2NotIn(List<Short> values) {
            addCriterion("id_manager_sf2 not in", values, "idManagerSf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf2Between(Short value1, Short value2) {
            addCriterion("id_manager_sf2 between", value1, value2, "idManagerSf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf2NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_sf2 not between", value1, value2, "idManagerSf2");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf3IsNull() {
            addCriterion("id_manager_sf3 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf3IsNotNull() {
            addCriterion("id_manager_sf3 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf3EqualTo(Short value) {
            addCriterion("id_manager_sf3 =", value, "idManagerSf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf3NotEqualTo(Short value) {
            addCriterion("id_manager_sf3 <>", value, "idManagerSf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf3GreaterThan(Short value) {
            addCriterion("id_manager_sf3 >", value, "idManagerSf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf3GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_sf3 >=", value, "idManagerSf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf3LessThan(Short value) {
            addCriterion("id_manager_sf3 <", value, "idManagerSf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf3LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_sf3 <=", value, "idManagerSf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf3In(List<Short> values) {
            addCriterion("id_manager_sf3 in", values, "idManagerSf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf3NotIn(List<Short> values) {
            addCriterion("id_manager_sf3 not in", values, "idManagerSf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf3Between(Short value1, Short value2) {
            addCriterion("id_manager_sf3 between", value1, value2, "idManagerSf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf3NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_sf3 not between", value1, value2, "idManagerSf3");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf4IsNull() {
            addCriterion("id_manager_sf4 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf4IsNotNull() {
            addCriterion("id_manager_sf4 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf4EqualTo(Short value) {
            addCriterion("id_manager_sf4 =", value, "idManagerSf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf4NotEqualTo(Short value) {
            addCriterion("id_manager_sf4 <>", value, "idManagerSf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf4GreaterThan(Short value) {
            addCriterion("id_manager_sf4 >", value, "idManagerSf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf4GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_sf4 >=", value, "idManagerSf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf4LessThan(Short value) {
            addCriterion("id_manager_sf4 <", value, "idManagerSf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf4LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_sf4 <=", value, "idManagerSf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf4In(List<Short> values) {
            addCriterion("id_manager_sf4 in", values, "idManagerSf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf4NotIn(List<Short> values) {
            addCriterion("id_manager_sf4 not in", values, "idManagerSf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf4Between(Short value1, Short value2) {
            addCriterion("id_manager_sf4 between", value1, value2, "idManagerSf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerSf4NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_sf4 not between", value1, value2, "idManagerSf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf1IsNull() {
            addCriterion("score_manager_sf1 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf1IsNotNull() {
            addCriterion("score_manager_sf1 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf1EqualTo(BigDecimal value) {
            addCriterion("score_manager_sf1 =", value, "scoreManagerSf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf1NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_sf1 <>", value, "scoreManagerSf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf1GreaterThan(BigDecimal value) {
            addCriterion("score_manager_sf1 >", value, "scoreManagerSf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_sf1 >=", value, "scoreManagerSf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf1LessThan(BigDecimal value) {
            addCriterion("score_manager_sf1 <", value, "scoreManagerSf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_sf1 <=", value, "scoreManagerSf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf1In(List<BigDecimal> values) {
            addCriterion("score_manager_sf1 in", values, "scoreManagerSf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf1NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_sf1 not in", values, "scoreManagerSf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_sf1 between", value1, value2, "scoreManagerSf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_sf1 not between", value1, value2, "scoreManagerSf1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf2IsNull() {
            addCriterion("score_manager_sf2 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf2IsNotNull() {
            addCriterion("score_manager_sf2 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf2EqualTo(BigDecimal value) {
            addCriterion("score_manager_sf2 =", value, "scoreManagerSf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf2NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_sf2 <>", value, "scoreManagerSf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf2GreaterThan(BigDecimal value) {
            addCriterion("score_manager_sf2 >", value, "scoreManagerSf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_sf2 >=", value, "scoreManagerSf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf2LessThan(BigDecimal value) {
            addCriterion("score_manager_sf2 <", value, "scoreManagerSf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_sf2 <=", value, "scoreManagerSf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf2In(List<BigDecimal> values) {
            addCriterion("score_manager_sf2 in", values, "scoreManagerSf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf2NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_sf2 not in", values, "scoreManagerSf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_sf2 between", value1, value2, "scoreManagerSf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_sf2 not between", value1, value2, "scoreManagerSf2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf3IsNull() {
            addCriterion("score_manager_sf3 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf3IsNotNull() {
            addCriterion("score_manager_sf3 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf3EqualTo(BigDecimal value) {
            addCriterion("score_manager_sf3 =", value, "scoreManagerSf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf3NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_sf3 <>", value, "scoreManagerSf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf3GreaterThan(BigDecimal value) {
            addCriterion("score_manager_sf3 >", value, "scoreManagerSf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf3GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_sf3 >=", value, "scoreManagerSf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf3LessThan(BigDecimal value) {
            addCriterion("score_manager_sf3 <", value, "scoreManagerSf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf3LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_sf3 <=", value, "scoreManagerSf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf3In(List<BigDecimal> values) {
            addCriterion("score_manager_sf3 in", values, "scoreManagerSf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf3NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_sf3 not in", values, "scoreManagerSf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf3Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_sf3 between", value1, value2, "scoreManagerSf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf3NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_sf3 not between", value1, value2, "scoreManagerSf3");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf4IsNull() {
            addCriterion("score_manager_sf4 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf4IsNotNull() {
            addCriterion("score_manager_sf4 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf4EqualTo(BigDecimal value) {
            addCriterion("score_manager_sf4 =", value, "scoreManagerSf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf4NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_sf4 <>", value, "scoreManagerSf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf4GreaterThan(BigDecimal value) {
            addCriterion("score_manager_sf4 >", value, "scoreManagerSf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf4GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_sf4 >=", value, "scoreManagerSf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf4LessThan(BigDecimal value) {
            addCriterion("score_manager_sf4 <", value, "scoreManagerSf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf4LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_sf4 <=", value, "scoreManagerSf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf4In(List<BigDecimal> values) {
            addCriterion("score_manager_sf4 in", values, "scoreManagerSf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf4NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_sf4 not in", values, "scoreManagerSf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf4Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_sf4 between", value1, value2, "scoreManagerSf4");
            return (Criteria) this;
        }

        public Criteria andScoreManagerSf4NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_sf4 not between", value1, value2, "scoreManagerSf4");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi1IsNull() {
            addCriterion("id_manager_fi1 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi1IsNotNull() {
            addCriterion("id_manager_fi1 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi1EqualTo(Short value) {
            addCriterion("id_manager_fi1 =", value, "idManagerFi1");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi1NotEqualTo(Short value) {
            addCriterion("id_manager_fi1 <>", value, "idManagerFi1");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi1GreaterThan(Short value) {
            addCriterion("id_manager_fi1 >", value, "idManagerFi1");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi1GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_fi1 >=", value, "idManagerFi1");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi1LessThan(Short value) {
            addCriterion("id_manager_fi1 <", value, "idManagerFi1");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi1LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_fi1 <=", value, "idManagerFi1");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi1In(List<Short> values) {
            addCriterion("id_manager_fi1 in", values, "idManagerFi1");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi1NotIn(List<Short> values) {
            addCriterion("id_manager_fi1 not in", values, "idManagerFi1");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi1Between(Short value1, Short value2) {
            addCriterion("id_manager_fi1 between", value1, value2, "idManagerFi1");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi1NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_fi1 not between", value1, value2, "idManagerFi1");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi2IsNull() {
            addCriterion("id_manager_fi2 is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi2IsNotNull() {
            addCriterion("id_manager_fi2 is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi2EqualTo(Short value) {
            addCriterion("id_manager_fi2 =", value, "idManagerFi2");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi2NotEqualTo(Short value) {
            addCriterion("id_manager_fi2 <>", value, "idManagerFi2");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi2GreaterThan(Short value) {
            addCriterion("id_manager_fi2 >", value, "idManagerFi2");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi2GreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_fi2 >=", value, "idManagerFi2");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi2LessThan(Short value) {
            addCriterion("id_manager_fi2 <", value, "idManagerFi2");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi2LessThanOrEqualTo(Short value) {
            addCriterion("id_manager_fi2 <=", value, "idManagerFi2");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi2In(List<Short> values) {
            addCriterion("id_manager_fi2 in", values, "idManagerFi2");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi2NotIn(List<Short> values) {
            addCriterion("id_manager_fi2 not in", values, "idManagerFi2");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi2Between(Short value1, Short value2) {
            addCriterion("id_manager_fi2 between", value1, value2, "idManagerFi2");
            return (Criteria) this;
        }

        public Criteria andIdManagerFi2NotBetween(Short value1, Short value2) {
            addCriterion("id_manager_fi2 not between", value1, value2, "idManagerFi2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi1IsNull() {
            addCriterion("score_manager_fi1 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi1IsNotNull() {
            addCriterion("score_manager_fi1 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi1EqualTo(BigDecimal value) {
            addCriterion("score_manager_fi1 =", value, "scoreManagerFi1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi1NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_fi1 <>", value, "scoreManagerFi1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi1GreaterThan(BigDecimal value) {
            addCriterion("score_manager_fi1 >", value, "scoreManagerFi1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_fi1 >=", value, "scoreManagerFi1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi1LessThan(BigDecimal value) {
            addCriterion("score_manager_fi1 <", value, "scoreManagerFi1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_fi1 <=", value, "scoreManagerFi1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi1In(List<BigDecimal> values) {
            addCriterion("score_manager_fi1 in", values, "scoreManagerFi1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi1NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_fi1 not in", values, "scoreManagerFi1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_fi1 between", value1, value2, "scoreManagerFi1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_fi1 not between", value1, value2, "scoreManagerFi1");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi2IsNull() {
            addCriterion("score_manager_fi2 is null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi2IsNotNull() {
            addCriterion("score_manager_fi2 is not null");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi2EqualTo(BigDecimal value) {
            addCriterion("score_manager_fi2 =", value, "scoreManagerFi2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi2NotEqualTo(BigDecimal value) {
            addCriterion("score_manager_fi2 <>", value, "scoreManagerFi2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi2GreaterThan(BigDecimal value) {
            addCriterion("score_manager_fi2 >", value, "scoreManagerFi2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_fi2 >=", value, "scoreManagerFi2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi2LessThan(BigDecimal value) {
            addCriterion("score_manager_fi2 <", value, "scoreManagerFi2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("score_manager_fi2 <=", value, "scoreManagerFi2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi2In(List<BigDecimal> values) {
            addCriterion("score_manager_fi2 in", values, "scoreManagerFi2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi2NotIn(List<BigDecimal> values) {
            addCriterion("score_manager_fi2 not in", values, "scoreManagerFi2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_fi2 between", value1, value2, "scoreManagerFi2");
            return (Criteria) this;
        }

        public Criteria andScoreManagerFi2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score_manager_fi2 not between", value1, value2, "scoreManagerFi2");
            return (Criteria) this;
        }

        public Criteria andIdManagerWinnerIsNull() {
            addCriterion("id_manager_winner is null");
            return (Criteria) this;
        }

        public Criteria andIdManagerWinnerIsNotNull() {
            addCriterion("id_manager_winner is not null");
            return (Criteria) this;
        }

        public Criteria andIdManagerWinnerEqualTo(Short value) {
            addCriterion("id_manager_winner =", value, "idManagerWinner");
            return (Criteria) this;
        }

        public Criteria andIdManagerWinnerNotEqualTo(Short value) {
            addCriterion("id_manager_winner <>", value, "idManagerWinner");
            return (Criteria) this;
        }

        public Criteria andIdManagerWinnerGreaterThan(Short value) {
            addCriterion("id_manager_winner >", value, "idManagerWinner");
            return (Criteria) this;
        }

        public Criteria andIdManagerWinnerGreaterThanOrEqualTo(Short value) {
            addCriterion("id_manager_winner >=", value, "idManagerWinner");
            return (Criteria) this;
        }

        public Criteria andIdManagerWinnerLessThan(Short value) {
            addCriterion("id_manager_winner <", value, "idManagerWinner");
            return (Criteria) this;
        }

        public Criteria andIdManagerWinnerLessThanOrEqualTo(Short value) {
            addCriterion("id_manager_winner <=", value, "idManagerWinner");
            return (Criteria) this;
        }

        public Criteria andIdManagerWinnerIn(List<Short> values) {
            addCriterion("id_manager_winner in", values, "idManagerWinner");
            return (Criteria) this;
        }

        public Criteria andIdManagerWinnerNotIn(List<Short> values) {
            addCriterion("id_manager_winner not in", values, "idManagerWinner");
            return (Criteria) this;
        }

        public Criteria andIdManagerWinnerBetween(Short value1, Short value2) {
            addCriterion("id_manager_winner between", value1, value2, "idManagerWinner");
            return (Criteria) this;
        }

        public Criteria andIdManagerWinnerNotBetween(Short value1, Short value2) {
            addCriterion("id_manager_winner not between", value1, value2, "idManagerWinner");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated do_not_delete_during_merge Sun Oct 16 14:56:04 CEST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cupstandingsnapshot
     *
     * @mbg.generated Sun Oct 16 14:56:04 CEST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}