package org.jlobato.gpro.dao.mybatis.model;

import java.io.Serializable;

public class Pitstop implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitstop.id_pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    private Integer idPitstop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitstop.id_racedata
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    private Integer idRacedata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitstop.pit_no
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    private Short pitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitstop.pit_lap
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    private Short pitLap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitstop.pit_reason
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    private String pitReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitstop.pit_tyres
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    private Short pitTyres;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitstop.pit_fuel
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    private Short pitFuel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitstop.pit_refill
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    private Short pitRefill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pitstop.pit_time
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    private Integer pitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitstop.id_pitstop
     *
     * @return the value of pitstop.id_pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Integer getIdPitstop() {
        return idPitstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Pitstop withIdPitstop(Integer idPitstop) {
        this.setIdPitstop(idPitstop);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitstop.id_pitstop
     *
     * @param idPitstop the value for pitstop.id_pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public void setIdPitstop(Integer idPitstop) {
        this.idPitstop = idPitstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitstop.id_racedata
     *
     * @return the value of pitstop.id_racedata
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Integer getIdRacedata() {
        return idRacedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Pitstop withIdRacedata(Integer idRacedata) {
        this.setIdRacedata(idRacedata);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitstop.id_racedata
     *
     * @param idRacedata the value for pitstop.id_racedata
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public void setIdRacedata(Integer idRacedata) {
        this.idRacedata = idRacedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitstop.pit_no
     *
     * @return the value of pitstop.pit_no
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Short getPitNo() {
        return pitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Pitstop withPitNo(Short pitNo) {
        this.setPitNo(pitNo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitstop.pit_no
     *
     * @param pitNo the value for pitstop.pit_no
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public void setPitNo(Short pitNo) {
        this.pitNo = pitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitstop.pit_lap
     *
     * @return the value of pitstop.pit_lap
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Short getPitLap() {
        return pitLap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Pitstop withPitLap(Short pitLap) {
        this.setPitLap(pitLap);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitstop.pit_lap
     *
     * @param pitLap the value for pitstop.pit_lap
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public void setPitLap(Short pitLap) {
        this.pitLap = pitLap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitstop.pit_reason
     *
     * @return the value of pitstop.pit_reason
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public String getPitReason() {
        return pitReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Pitstop withPitReason(String pitReason) {
        this.setPitReason(pitReason);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitstop.pit_reason
     *
     * @param pitReason the value for pitstop.pit_reason
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public void setPitReason(String pitReason) {
        this.pitReason = pitReason == null ? null : pitReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitstop.pit_tyres
     *
     * @return the value of pitstop.pit_tyres
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Short getPitTyres() {
        return pitTyres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Pitstop withPitTyres(Short pitTyres) {
        this.setPitTyres(pitTyres);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitstop.pit_tyres
     *
     * @param pitTyres the value for pitstop.pit_tyres
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public void setPitTyres(Short pitTyres) {
        this.pitTyres = pitTyres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitstop.pit_fuel
     *
     * @return the value of pitstop.pit_fuel
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Short getPitFuel() {
        return pitFuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Pitstop withPitFuel(Short pitFuel) {
        this.setPitFuel(pitFuel);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitstop.pit_fuel
     *
     * @param pitFuel the value for pitstop.pit_fuel
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public void setPitFuel(Short pitFuel) {
        this.pitFuel = pitFuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitstop.pit_refill
     *
     * @return the value of pitstop.pit_refill
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Short getPitRefill() {
        return pitRefill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Pitstop withPitRefill(Short pitRefill) {
        this.setPitRefill(pitRefill);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitstop.pit_refill
     *
     * @param pitRefill the value for pitstop.pit_refill
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public void setPitRefill(Short pitRefill) {
        this.pitRefill = pitRefill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pitstop.pit_time
     *
     * @return the value of pitstop.pit_time
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Integer getPitTime() {
        return pitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public Pitstop withPitTime(Integer pitTime) {
        this.setPitTime(pitTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pitstop.pit_time
     *
     * @param pitTime the value for pitstop.pit_time
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    public void setPitTime(Integer pitTime) {
        this.pitTime = pitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pitstop
     *
     * @mbg.generated Sun May 16 18:22:26 CEST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idPitstop=").append(idPitstop);
        sb.append(", idRacedata=").append(idRacedata);
        sb.append(", pitNo=").append(pitNo);
        sb.append(", pitLap=").append(pitLap);
        sb.append(", pitReason=").append(pitReason);
        sb.append(", pitTyres=").append(pitTyres);
        sb.append(", pitFuel=").append(pitFuel);
        sb.append(", pitRefill=").append(pitRefill);
        sb.append(", pitTime=").append(pitTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}