package org.jlobato.gpro.dao.mybatis.model;

import java.io.Serializable;

public class RaceData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.id_racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Integer idRacedata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.id_season
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short idSeason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.id_race
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short idRace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.id_track
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short idTrack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.id_manager
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short idManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.overtake_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short overtakeRisks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.defend_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short defendRisks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.dry_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short dryRisks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.wet_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short wetRisks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.malfunction_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short malfunctionRisks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.setup_fw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short setupFw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.setup_rw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short setupRw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.setup_en
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short setupEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.setup_br
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short setupBr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.setup_ge
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short setupGe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.setup_su
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short setupSu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.carlvl_ch
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short carlvlCh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.carlvl_en
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short carlvlEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.carlvl_fw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short carlvlFw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.carlvl_rw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short carlvlRw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.carlvl_un
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short carlvlUn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.carlvl_si
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short carlvlSi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.carlvl_co
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short carlvlCo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.carlvl_ge
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short carlvlGe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.carlvl_br
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short carlvlBr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.carlvl_su
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short carlvlSu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.carlvl_el
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short carlvlEl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weasta_ch
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weastaCh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weasta_en
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weastaEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weasta_fw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weastaFw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weasta_rw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weastaRw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weasta_un
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weastaUn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weasta_si
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weastaSi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weasta_co
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weastaCo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weasta_ge
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weastaGe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weasta_br
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weastaBr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weasta_su
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weastaSu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weasta_el
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weastaEl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weaend_ch
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weaendCh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weaend_en
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weaendEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weaend_fw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weaendFw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weaend_rw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weaendRw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weaend_un
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weaendUn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weaend_si
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weaendSi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weaend_co
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weaendCo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weaend_ge
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weaendGe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weaend_br
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weaendBr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weaend_su
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weaendSu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.weaend_el
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short weaendEl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.fuel_sta
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short fuelSta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.fuel_end
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short fuelEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racedata.tyr_end
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private Short tyrEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.id_racedata
     *
     * @return the value of racedata.id_racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Integer getIdRacedata() {
        return idRacedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withIdRacedata(Integer idRacedata) {
        this.setIdRacedata(idRacedata);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.id_racedata
     *
     * @param idRacedata the value for racedata.id_racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setIdRacedata(Integer idRacedata) {
        this.idRacedata = idRacedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.id_season
     *
     * @return the value of racedata.id_season
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getIdSeason() {
        return idSeason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withIdSeason(Short idSeason) {
        this.setIdSeason(idSeason);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.id_season
     *
     * @param idSeason the value for racedata.id_season
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setIdSeason(Short idSeason) {
        this.idSeason = idSeason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.id_race
     *
     * @return the value of racedata.id_race
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getIdRace() {
        return idRace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withIdRace(Short idRace) {
        this.setIdRace(idRace);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.id_race
     *
     * @param idRace the value for racedata.id_race
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setIdRace(Short idRace) {
        this.idRace = idRace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.id_track
     *
     * @return the value of racedata.id_track
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getIdTrack() {
        return idTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withIdTrack(Short idTrack) {
        this.setIdTrack(idTrack);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.id_track
     *
     * @param idTrack the value for racedata.id_track
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setIdTrack(Short idTrack) {
        this.idTrack = idTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.id_manager
     *
     * @return the value of racedata.id_manager
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getIdManager() {
        return idManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withIdManager(Short idManager) {
        this.setIdManager(idManager);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.id_manager
     *
     * @param idManager the value for racedata.id_manager
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setIdManager(Short idManager) {
        this.idManager = idManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.overtake_risks
     *
     * @return the value of racedata.overtake_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getOvertakeRisks() {
        return overtakeRisks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withOvertakeRisks(Short overtakeRisks) {
        this.setOvertakeRisks(overtakeRisks);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.overtake_risks
     *
     * @param overtakeRisks the value for racedata.overtake_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setOvertakeRisks(Short overtakeRisks) {
        this.overtakeRisks = overtakeRisks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.defend_risks
     *
     * @return the value of racedata.defend_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getDefendRisks() {
        return defendRisks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withDefendRisks(Short defendRisks) {
        this.setDefendRisks(defendRisks);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.defend_risks
     *
     * @param defendRisks the value for racedata.defend_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setDefendRisks(Short defendRisks) {
        this.defendRisks = defendRisks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.dry_risks
     *
     * @return the value of racedata.dry_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getDryRisks() {
        return dryRisks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withDryRisks(Short dryRisks) {
        this.setDryRisks(dryRisks);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.dry_risks
     *
     * @param dryRisks the value for racedata.dry_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setDryRisks(Short dryRisks) {
        this.dryRisks = dryRisks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.wet_risks
     *
     * @return the value of racedata.wet_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWetRisks() {
        return wetRisks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWetRisks(Short wetRisks) {
        this.setWetRisks(wetRisks);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.wet_risks
     *
     * @param wetRisks the value for racedata.wet_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWetRisks(Short wetRisks) {
        this.wetRisks = wetRisks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.malfunction_risks
     *
     * @return the value of racedata.malfunction_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getMalfunctionRisks() {
        return malfunctionRisks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withMalfunctionRisks(Short malfunctionRisks) {
        this.setMalfunctionRisks(malfunctionRisks);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.malfunction_risks
     *
     * @param malfunctionRisks the value for racedata.malfunction_risks
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setMalfunctionRisks(Short malfunctionRisks) {
        this.malfunctionRisks = malfunctionRisks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.setup_fw
     *
     * @return the value of racedata.setup_fw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getSetupFw() {
        return setupFw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withSetupFw(Short setupFw) {
        this.setSetupFw(setupFw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.setup_fw
     *
     * @param setupFw the value for racedata.setup_fw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setSetupFw(Short setupFw) {
        this.setupFw = setupFw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.setup_rw
     *
     * @return the value of racedata.setup_rw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getSetupRw() {
        return setupRw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withSetupRw(Short setupRw) {
        this.setSetupRw(setupRw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.setup_rw
     *
     * @param setupRw the value for racedata.setup_rw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setSetupRw(Short setupRw) {
        this.setupRw = setupRw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.setup_en
     *
     * @return the value of racedata.setup_en
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getSetupEn() {
        return setupEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withSetupEn(Short setupEn) {
        this.setSetupEn(setupEn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.setup_en
     *
     * @param setupEn the value for racedata.setup_en
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setSetupEn(Short setupEn) {
        this.setupEn = setupEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.setup_br
     *
     * @return the value of racedata.setup_br
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getSetupBr() {
        return setupBr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withSetupBr(Short setupBr) {
        this.setSetupBr(setupBr);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.setup_br
     *
     * @param setupBr the value for racedata.setup_br
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setSetupBr(Short setupBr) {
        this.setupBr = setupBr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.setup_ge
     *
     * @return the value of racedata.setup_ge
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getSetupGe() {
        return setupGe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withSetupGe(Short setupGe) {
        this.setSetupGe(setupGe);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.setup_ge
     *
     * @param setupGe the value for racedata.setup_ge
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setSetupGe(Short setupGe) {
        this.setupGe = setupGe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.setup_su
     *
     * @return the value of racedata.setup_su
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getSetupSu() {
        return setupSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withSetupSu(Short setupSu) {
        this.setSetupSu(setupSu);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.setup_su
     *
     * @param setupSu the value for racedata.setup_su
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setSetupSu(Short setupSu) {
        this.setupSu = setupSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.carlvl_ch
     *
     * @return the value of racedata.carlvl_ch
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getCarlvlCh() {
        return carlvlCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withCarlvlCh(Short carlvlCh) {
        this.setCarlvlCh(carlvlCh);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.carlvl_ch
     *
     * @param carlvlCh the value for racedata.carlvl_ch
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setCarlvlCh(Short carlvlCh) {
        this.carlvlCh = carlvlCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.carlvl_en
     *
     * @return the value of racedata.carlvl_en
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getCarlvlEn() {
        return carlvlEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withCarlvlEn(Short carlvlEn) {
        this.setCarlvlEn(carlvlEn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.carlvl_en
     *
     * @param carlvlEn the value for racedata.carlvl_en
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setCarlvlEn(Short carlvlEn) {
        this.carlvlEn = carlvlEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.carlvl_fw
     *
     * @return the value of racedata.carlvl_fw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getCarlvlFw() {
        return carlvlFw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withCarlvlFw(Short carlvlFw) {
        this.setCarlvlFw(carlvlFw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.carlvl_fw
     *
     * @param carlvlFw the value for racedata.carlvl_fw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setCarlvlFw(Short carlvlFw) {
        this.carlvlFw = carlvlFw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.carlvl_rw
     *
     * @return the value of racedata.carlvl_rw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getCarlvlRw() {
        return carlvlRw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withCarlvlRw(Short carlvlRw) {
        this.setCarlvlRw(carlvlRw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.carlvl_rw
     *
     * @param carlvlRw the value for racedata.carlvl_rw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setCarlvlRw(Short carlvlRw) {
        this.carlvlRw = carlvlRw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.carlvl_un
     *
     * @return the value of racedata.carlvl_un
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getCarlvlUn() {
        return carlvlUn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withCarlvlUn(Short carlvlUn) {
        this.setCarlvlUn(carlvlUn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.carlvl_un
     *
     * @param carlvlUn the value for racedata.carlvl_un
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setCarlvlUn(Short carlvlUn) {
        this.carlvlUn = carlvlUn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.carlvl_si
     *
     * @return the value of racedata.carlvl_si
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getCarlvlSi() {
        return carlvlSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withCarlvlSi(Short carlvlSi) {
        this.setCarlvlSi(carlvlSi);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.carlvl_si
     *
     * @param carlvlSi the value for racedata.carlvl_si
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setCarlvlSi(Short carlvlSi) {
        this.carlvlSi = carlvlSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.carlvl_co
     *
     * @return the value of racedata.carlvl_co
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getCarlvlCo() {
        return carlvlCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withCarlvlCo(Short carlvlCo) {
        this.setCarlvlCo(carlvlCo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.carlvl_co
     *
     * @param carlvlCo the value for racedata.carlvl_co
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setCarlvlCo(Short carlvlCo) {
        this.carlvlCo = carlvlCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.carlvl_ge
     *
     * @return the value of racedata.carlvl_ge
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getCarlvlGe() {
        return carlvlGe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withCarlvlGe(Short carlvlGe) {
        this.setCarlvlGe(carlvlGe);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.carlvl_ge
     *
     * @param carlvlGe the value for racedata.carlvl_ge
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setCarlvlGe(Short carlvlGe) {
        this.carlvlGe = carlvlGe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.carlvl_br
     *
     * @return the value of racedata.carlvl_br
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getCarlvlBr() {
        return carlvlBr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withCarlvlBr(Short carlvlBr) {
        this.setCarlvlBr(carlvlBr);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.carlvl_br
     *
     * @param carlvlBr the value for racedata.carlvl_br
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setCarlvlBr(Short carlvlBr) {
        this.carlvlBr = carlvlBr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.carlvl_su
     *
     * @return the value of racedata.carlvl_su
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getCarlvlSu() {
        return carlvlSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withCarlvlSu(Short carlvlSu) {
        this.setCarlvlSu(carlvlSu);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.carlvl_su
     *
     * @param carlvlSu the value for racedata.carlvl_su
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setCarlvlSu(Short carlvlSu) {
        this.carlvlSu = carlvlSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.carlvl_el
     *
     * @return the value of racedata.carlvl_el
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getCarlvlEl() {
        return carlvlEl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withCarlvlEl(Short carlvlEl) {
        this.setCarlvlEl(carlvlEl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.carlvl_el
     *
     * @param carlvlEl the value for racedata.carlvl_el
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setCarlvlEl(Short carlvlEl) {
        this.carlvlEl = carlvlEl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weasta_ch
     *
     * @return the value of racedata.weasta_ch
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeastaCh() {
        return weastaCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeastaCh(Short weastaCh) {
        this.setWeastaCh(weastaCh);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weasta_ch
     *
     * @param weastaCh the value for racedata.weasta_ch
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeastaCh(Short weastaCh) {
        this.weastaCh = weastaCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weasta_en
     *
     * @return the value of racedata.weasta_en
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeastaEn() {
        return weastaEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeastaEn(Short weastaEn) {
        this.setWeastaEn(weastaEn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weasta_en
     *
     * @param weastaEn the value for racedata.weasta_en
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeastaEn(Short weastaEn) {
        this.weastaEn = weastaEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weasta_fw
     *
     * @return the value of racedata.weasta_fw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeastaFw() {
        return weastaFw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeastaFw(Short weastaFw) {
        this.setWeastaFw(weastaFw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weasta_fw
     *
     * @param weastaFw the value for racedata.weasta_fw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeastaFw(Short weastaFw) {
        this.weastaFw = weastaFw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weasta_rw
     *
     * @return the value of racedata.weasta_rw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeastaRw() {
        return weastaRw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeastaRw(Short weastaRw) {
        this.setWeastaRw(weastaRw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weasta_rw
     *
     * @param weastaRw the value for racedata.weasta_rw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeastaRw(Short weastaRw) {
        this.weastaRw = weastaRw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weasta_un
     *
     * @return the value of racedata.weasta_un
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeastaUn() {
        return weastaUn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeastaUn(Short weastaUn) {
        this.setWeastaUn(weastaUn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weasta_un
     *
     * @param weastaUn the value for racedata.weasta_un
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeastaUn(Short weastaUn) {
        this.weastaUn = weastaUn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weasta_si
     *
     * @return the value of racedata.weasta_si
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeastaSi() {
        return weastaSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeastaSi(Short weastaSi) {
        this.setWeastaSi(weastaSi);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weasta_si
     *
     * @param weastaSi the value for racedata.weasta_si
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeastaSi(Short weastaSi) {
        this.weastaSi = weastaSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weasta_co
     *
     * @return the value of racedata.weasta_co
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeastaCo() {
        return weastaCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeastaCo(Short weastaCo) {
        this.setWeastaCo(weastaCo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weasta_co
     *
     * @param weastaCo the value for racedata.weasta_co
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeastaCo(Short weastaCo) {
        this.weastaCo = weastaCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weasta_ge
     *
     * @return the value of racedata.weasta_ge
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeastaGe() {
        return weastaGe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeastaGe(Short weastaGe) {
        this.setWeastaGe(weastaGe);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weasta_ge
     *
     * @param weastaGe the value for racedata.weasta_ge
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeastaGe(Short weastaGe) {
        this.weastaGe = weastaGe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weasta_br
     *
     * @return the value of racedata.weasta_br
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeastaBr() {
        return weastaBr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeastaBr(Short weastaBr) {
        this.setWeastaBr(weastaBr);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weasta_br
     *
     * @param weastaBr the value for racedata.weasta_br
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeastaBr(Short weastaBr) {
        this.weastaBr = weastaBr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weasta_su
     *
     * @return the value of racedata.weasta_su
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeastaSu() {
        return weastaSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeastaSu(Short weastaSu) {
        this.setWeastaSu(weastaSu);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weasta_su
     *
     * @param weastaSu the value for racedata.weasta_su
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeastaSu(Short weastaSu) {
        this.weastaSu = weastaSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weasta_el
     *
     * @return the value of racedata.weasta_el
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeastaEl() {
        return weastaEl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeastaEl(Short weastaEl) {
        this.setWeastaEl(weastaEl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weasta_el
     *
     * @param weastaEl the value for racedata.weasta_el
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeastaEl(Short weastaEl) {
        this.weastaEl = weastaEl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weaend_ch
     *
     * @return the value of racedata.weaend_ch
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeaendCh() {
        return weaendCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeaendCh(Short weaendCh) {
        this.setWeaendCh(weaendCh);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weaend_ch
     *
     * @param weaendCh the value for racedata.weaend_ch
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeaendCh(Short weaendCh) {
        this.weaendCh = weaendCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weaend_en
     *
     * @return the value of racedata.weaend_en
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeaendEn() {
        return weaendEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeaendEn(Short weaendEn) {
        this.setWeaendEn(weaendEn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weaend_en
     *
     * @param weaendEn the value for racedata.weaend_en
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeaendEn(Short weaendEn) {
        this.weaendEn = weaendEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weaend_fw
     *
     * @return the value of racedata.weaend_fw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeaendFw() {
        return weaendFw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeaendFw(Short weaendFw) {
        this.setWeaendFw(weaendFw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weaend_fw
     *
     * @param weaendFw the value for racedata.weaend_fw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeaendFw(Short weaendFw) {
        this.weaendFw = weaendFw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weaend_rw
     *
     * @return the value of racedata.weaend_rw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeaendRw() {
        return weaendRw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeaendRw(Short weaendRw) {
        this.setWeaendRw(weaendRw);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weaend_rw
     *
     * @param weaendRw the value for racedata.weaend_rw
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeaendRw(Short weaendRw) {
        this.weaendRw = weaendRw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weaend_un
     *
     * @return the value of racedata.weaend_un
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeaendUn() {
        return weaendUn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeaendUn(Short weaendUn) {
        this.setWeaendUn(weaendUn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weaend_un
     *
     * @param weaendUn the value for racedata.weaend_un
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeaendUn(Short weaendUn) {
        this.weaendUn = weaendUn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weaend_si
     *
     * @return the value of racedata.weaend_si
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeaendSi() {
        return weaendSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeaendSi(Short weaendSi) {
        this.setWeaendSi(weaendSi);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weaend_si
     *
     * @param weaendSi the value for racedata.weaend_si
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeaendSi(Short weaendSi) {
        this.weaendSi = weaendSi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weaend_co
     *
     * @return the value of racedata.weaend_co
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeaendCo() {
        return weaendCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeaendCo(Short weaendCo) {
        this.setWeaendCo(weaendCo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weaend_co
     *
     * @param weaendCo the value for racedata.weaend_co
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeaendCo(Short weaendCo) {
        this.weaendCo = weaendCo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weaend_ge
     *
     * @return the value of racedata.weaend_ge
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeaendGe() {
        return weaendGe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeaendGe(Short weaendGe) {
        this.setWeaendGe(weaendGe);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weaend_ge
     *
     * @param weaendGe the value for racedata.weaend_ge
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeaendGe(Short weaendGe) {
        this.weaendGe = weaendGe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weaend_br
     *
     * @return the value of racedata.weaend_br
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeaendBr() {
        return weaendBr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeaendBr(Short weaendBr) {
        this.setWeaendBr(weaendBr);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weaend_br
     *
     * @param weaendBr the value for racedata.weaend_br
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeaendBr(Short weaendBr) {
        this.weaendBr = weaendBr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weaend_su
     *
     * @return the value of racedata.weaend_su
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeaendSu() {
        return weaendSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeaendSu(Short weaendSu) {
        this.setWeaendSu(weaendSu);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weaend_su
     *
     * @param weaendSu the value for racedata.weaend_su
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeaendSu(Short weaendSu) {
        this.weaendSu = weaendSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.weaend_el
     *
     * @return the value of racedata.weaend_el
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getWeaendEl() {
        return weaendEl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withWeaendEl(Short weaendEl) {
        this.setWeaendEl(weaendEl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.weaend_el
     *
     * @param weaendEl the value for racedata.weaend_el
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setWeaendEl(Short weaendEl) {
        this.weaendEl = weaendEl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.fuel_sta
     *
     * @return the value of racedata.fuel_sta
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getFuelSta() {
        return fuelSta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withFuelSta(Short fuelSta) {
        this.setFuelSta(fuelSta);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.fuel_sta
     *
     * @param fuelSta the value for racedata.fuel_sta
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setFuelSta(Short fuelSta) {
        this.fuelSta = fuelSta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.fuel_end
     *
     * @return the value of racedata.fuel_end
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getFuelEnd() {
        return fuelEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withFuelEnd(Short fuelEnd) {
        this.setFuelEnd(fuelEnd);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.fuel_end
     *
     * @param fuelEnd the value for racedata.fuel_end
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setFuelEnd(Short fuelEnd) {
        this.fuelEnd = fuelEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racedata.tyr_end
     *
     * @return the value of racedata.tyr_end
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public Short getTyrEnd() {
        return tyrEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public RaceData withTyrEnd(Short tyrEnd) {
        this.setTyrEnd(tyrEnd);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racedata.tyr_end
     *
     * @param tyrEnd the value for racedata.tyr_end
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    public void setTyrEnd(Short tyrEnd) {
        this.tyrEnd = tyrEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racedata
     *
     * @mbg.generated Sun Oct 16 16:30:16 CEST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idRacedata=").append(idRacedata);
        sb.append(", idSeason=").append(idSeason);
        sb.append(", idRace=").append(idRace);
        sb.append(", idTrack=").append(idTrack);
        sb.append(", idManager=").append(idManager);
        sb.append(", overtakeRisks=").append(overtakeRisks);
        sb.append(", defendRisks=").append(defendRisks);
        sb.append(", dryRisks=").append(dryRisks);
        sb.append(", wetRisks=").append(wetRisks);
        sb.append(", malfunctionRisks=").append(malfunctionRisks);
        sb.append(", setupFw=").append(setupFw);
        sb.append(", setupRw=").append(setupRw);
        sb.append(", setupEn=").append(setupEn);
        sb.append(", setupBr=").append(setupBr);
        sb.append(", setupGe=").append(setupGe);
        sb.append(", setupSu=").append(setupSu);
        sb.append(", carlvlCh=").append(carlvlCh);
        sb.append(", carlvlEn=").append(carlvlEn);
        sb.append(", carlvlFw=").append(carlvlFw);
        sb.append(", carlvlRw=").append(carlvlRw);
        sb.append(", carlvlUn=").append(carlvlUn);
        sb.append(", carlvlSi=").append(carlvlSi);
        sb.append(", carlvlCo=").append(carlvlCo);
        sb.append(", carlvlGe=").append(carlvlGe);
        sb.append(", carlvlBr=").append(carlvlBr);
        sb.append(", carlvlSu=").append(carlvlSu);
        sb.append(", carlvlEl=").append(carlvlEl);
        sb.append(", weastaCh=").append(weastaCh);
        sb.append(", weastaEn=").append(weastaEn);
        sb.append(", weastaFw=").append(weastaFw);
        sb.append(", weastaRw=").append(weastaRw);
        sb.append(", weastaUn=").append(weastaUn);
        sb.append(", weastaSi=").append(weastaSi);
        sb.append(", weastaCo=").append(weastaCo);
        sb.append(", weastaGe=").append(weastaGe);
        sb.append(", weastaBr=").append(weastaBr);
        sb.append(", weastaSu=").append(weastaSu);
        sb.append(", weastaEl=").append(weastaEl);
        sb.append(", weaendCh=").append(weaendCh);
        sb.append(", weaendEn=").append(weaendEn);
        sb.append(", weaendFw=").append(weaendFw);
        sb.append(", weaendRw=").append(weaendRw);
        sb.append(", weaendUn=").append(weaendUn);
        sb.append(", weaendSi=").append(weaendSi);
        sb.append(", weaendCo=").append(weaendCo);
        sb.append(", weaendGe=").append(weaendGe);
        sb.append(", weaendBr=").append(weaendBr);
        sb.append(", weaendSu=").append(weaendSu);
        sb.append(", weaendEl=").append(weaendEl);
        sb.append(", fuelSta=").append(fuelSta);
        sb.append(", fuelEnd=").append(fuelEnd);
        sb.append(", tyrEnd=").append(tyrEnd);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}